version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4:4.26
    environment:
      PGADMIN_DEFAULT_PASSWORD : secret
      PGADMIN_DEFAULT_EMAIL : abdeljalil.aitetaleb@gmail.com
    ports:
      - "80:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: elearn
    ports:
      - "5432:5432"